### ISSUE TITLE
Replace hardcoded '/opt' in project_path in spark job with PROJECT_HOME env

### ISSUE THREAD

**Issue by lmaczulajtys** [getindata/kedro-airflow-k8s#128]
In Spark jobs, init script already sets PROJECT_HOME variable.

Line:
https://github.com/getindata/kedro-airflow-k8s/blob/83e7473c9825724b17571cd13b7ad53925e6e9f6/kedro_airflow_k8s/airflow_spark_task_template.j2#L9
should be replaced  with something like this: `project_path = os.getenv('PROJECT_HOME','/opt/{{ project_name }}')`

In some cases, I need to use different path for project. Thanks to that change, I could use `spark.yarn.appMasterEnv.PROJECT_HOME` in operator factory to change default /opt path.

**Comment by em-pe** [comment]
@lmaczulajtys would you mind submitting a PR for that one? Something like `project_path = os.getenv('PROJECT_HOME','/opt/{{ project_name }}')` I'd approve right away.
