### ISSUE TITLE
Select pipeline for DAG generation

### ISSUE THREAD

**Issue by michalzelechowski-getindata** [getindata/kedro-airflow-k8s#54]
Similar to vanilla `kedro` -p option, which selects pipeline to be operated, `airflow-k8s` plugin could allow selection of specific pipeline for DAG generation.
That functionality could be useful in bigger projects, were pipelines are complex, can be separated but share common nodes.

**Comment by michalzelechowski-getindata** [comment]
@em-pe Do you think CLI parameter would be sufficient or we should allow this to be part of the config? In case of config, we could use it for separation of runtime parameters.

**Comment by em-pe** [comment]
@michalzelechowski-getindata CLI should be sufficient I think
