### ISSUE TITLE
Customize start_date in DAG

### ISSUE THREAD

**Issue by michalzelechowski-getindata** [getindata/kedro-airflow-k8s#61]
It's currently set as constant, to `days_ago(2)`.

**Comment by szczeles** [comment]
@michalzelechowski-getindata  Also, you can leave it as constant and add `catchup=False` - Airflow will start only the latest execution

**Comment by michalzelechowski-getindata** [comment]
Eventually`start_date` has been implemented as an optional config attribute, as there we found a use case that somebody is willing to set it up.
