### ISSUE TITLE
Invalid configuration generated by `kedro airflow-k8s init`

### ISSUE THREAD

**Issue by szczeles** [getindata/kedro-airflow-k8s#87]
It looks one of the comments in sample config has a line break.

Steps to reproduce:
1. Install `kedro-airflow-k8s==0.6.3`
2. Run `kedro airflow-k8s init airlfow-url`
3. Run YAML linter on `conf/base/airflow-k8s.yaml`, the result is:

```
(<unknown>): found character that cannot start any token while scanning for the next token at line 68 column 13
```

**Comment by mariusz89016** [comment]
I've tried that with `kedro-airflow-k8s==0.7.3` and there were only warnings (`yamllint==1.26.3`, `relaxed` config): 
* `too many blank lines`
* `line too long (..)`
* `too many spaces after hyphen`
 
Is it ok?

**Comment by szczeles** [comment]
Yep, I believe it's fixed already, thanks for checking @mariusz89016  and @michalzelechowski-getindata !
