### ISSUE TITLE
kedro-airflow-k8s[gcp] depends on nonexistent library 

### ISSUE THREAD

**Issue by em-pe** [getindata/kedro-airflow-k8s#88]
Currently there are no versions on pypi that would fit the condition gcsfs>=0.6.3, <0.7.0
https://pypi.org/project/gcsfs/#history

**Comment by michalzelechowski-getindata** [comment]
@szczeles Is this issue eligible for closing after your last change?

**Comment by szczeles** [comment]
@michalzelechowski-getindata Yep, thanks for the redminder ;-)
